### ISSUE TITLE
check(): NOTE: "non-portable file paths"

### ISSUE THREAD

**Issue by dschlaep** [DrylandEcology/rSFSW2#157]
> NOTE: Found the following non-portable file paths:
> Tarballs are only required to store paths of up to 100 bytes and cannot
> store those of more than 256 bytes, with restrictions including to 100
> bytes for the final component.
> See section ‘Package structure’ in the ‘Writing R Extensions’ manual.

This note arises because of using a 'test project' (with deep folder hierarchy and long path names) as a unit test with commit e76daaac502d2b331256bd6d109c3e318500f79f

**Comment by Zachary-Kramer** [comment]
Out of previous experience with file paths and general curiosity, I wanted to find a solution to this, but it seems there's not really a way around it...will just have to shorten the folder hierarchy and/or names.

> The tar command looks for archives on the default device (usually tape), unless you specify another device with the -f Archive flag. When specifying path names that are greater than 100 characters for the United States Tape Archiver (USTAR) format, remember that the path name is composed of a prefix buffer, a / (slash), and a name buffer.

> The prefix buffer can be a maximum of 155 bytes and the name buffer can hold a maximum of 100 bytes. If the path name cannot be split into these two parts by a slash, it cannot be archived. This limitation is due to the structure of the tar archive headers, and must be maintained for compliance with standards and backwards compatibility. In additon, the length of a destination for a hard or symbolic link ( the 'link name') cannot exceed 100 bytes.

**Comment by dschlaep** [comment]
Thanks for the insights!

I added a 'low priority' label. These long file paths are only because of the unit test 'test project' folder. That means that they are irrelevant for installing and running the package. If we ever move forward and submit to cran or similar R package deployment, then we would not include the unit test folder.
