### ISSUE TITLE
Output aggregation: start/end DOY for snowpack/snowcover

### ISSUE THREAD

**Issue by dschlaep** [DrylandEcology/rSFSW2#219]
Overall aggregation option 'dailySnowpack' gains four new output variables:
- day of year when snowpack (= longest continuous snowpack period) starts
- day of year when snowpack (= longest continuous snowpack period) ends
- day of year when snow cover starts (= first day of water year with any snow cover) 
- day of year when snow cover ends (= last day of water year with any snow cover)

**Comment by CaitlinA** [comment]
@Zachary-Kramer Please work on this enhancement

**Comment by Zachary-Kramer** [comment]
What is the difference between the longest continuous snowpack period and the longest continuous snowcover period?

**Comment by dschlaep** [comment]
I would say that `longest continuous snowpack period` and `longest continuous snowcover period` mean the same thing. Why does the question arise?

**Comment by Zachary-Kramer** [comment]
Because the last DOY for continuous snow cover seems to already be implemented. I didn't know if I was supposed to implement something else for it.

![image](https://user-images.githubusercontent.com/16931318/34083209-bd69bec2-e36c-11e7-8dd7-4a75a61f1922.png)

Is that what you were requesting for 

> day of year when snowpack (= longest continuous snowpack period) ends

**Comment by dschlaep** [comment]
Ok, this is already implemented in this case.

**Comment by Zachary-Kramer** [comment]
Do the following values seem reasonable? My concern is that some values are negative, which is because they are subtracting `adjDays` which is 92 in this case:

| LongestContinuous_FirstDay | LongestContinuous_LastDay | LongestContinuous_Duration | Total_days | Peak    | SnowCover_FirstDay | SnowCover_LastDay |
|----------------------------|---------------------------|----------------------------|------------|---------|--------------------|-------------------|
| -65.033                    | 179.333                   | 244.367                    | 250.033    | 780.913 | -73.833            | 208.333           |

**Comment by dschlaep** [comment]
The `adjDays = 92` describes that the water year in the northern hemisphere is Oct 1 = 273 doy.

However, all output are in units of `day of year` and their values range between 1 and 366. Hence, you have to use `circ_mean` and `circ_sd` instead of `mean` and `sd` to calculate the average across years -- as you can see in the existing code.

I see no reason why you should not be able to pass negative values to `circ_mean`.
For instance,
```
all.equal(pi/2, rSFSW2:::circ_mean(-pi/2, int = pi))
[1] TRUE
```

**Comment by Zachary-Kramer** [comment]
> However, all output are in units of day of year and their values range between 1 and 366.

Okay, that's what I was wondering. `circ_mean` can certainly handle negative values, I just didn't know if we wanted to retain the negative days due to the water year.

**Comment by Zachary-Kramer** [comment]
So, you are expecting the values to be something like `SnowCover_FirstDay = 291` and `SnowCover_LastDay = 200`, correct? I just want to confirm that the last DOY should be less than the first DOY before I push it

**Comment by dschlaep** [comment]
I see four possible situations for sites in the northern hemisphere
- `normal`: snow cover starts in fall of one year and ends in spring of the following calendar year --> `SnowCover_FirstDOY > SnowCover_LastDOY`
- `late`: snow cover starts only after the new calendar year and ends in spring of the same calendar year --> `SnowCover_FirstDOY < SnowCover_LastDOY`
- `early`: snow cover starts in fall of one year and ends before the end of the same calendar year  --> `SnowCover_FirstDOY < SnowCover_LastDOY`
- `no snow`: `SnowCover_FirstDOY = SnowCover_LastDOY = NA`

**Comment by Zachary-Kramer** [comment]
The pushed branch is functional for me. To get the automated tests to pass, the reference DB will need to be updated. It would be most convenient to get the first pull request merged, merge master into this branch, and then update the reference DB.

**Comment by CaitlinA** [comment]
Closed with pull https://github.com/DrylandEcology/rSFSW2/pull/237
