### ISSUE TITLE
Output aggregation: number of cool days

### ISSUE THREAD

**Issue by dschlaep** [DrylandEcology/rSFSW2#222]
Comparable to how `dailyWarmDays` counts the number of days with mean daily temperature > `Tmean_crit_C`, we need a new output aggregation option `dailyCoolDays`.

`TmeanSurfaceBelowNegXC_days` = number of days with mean daily **surface** temperature < `Tmean_crit_C`.

**Comment by CaitlinA** [comment]
@Zachary-Kramer Please work on this enhancement

**Comment by CaitlinA** [comment]
Implementation merged with master 4b3ad1e
