### ISSUE TITLE
Output aggregation: dailyThermalDrynessStress for cold & dry

### ISSUE THREAD

**Issue by dschlaep** [DrylandEcology/rSFSW2#223]
Overall aggregation option `dailyThermalDrynessStress` gains new output variables for cold and dry conditions. 

Currently, `dailyThermalDrynessStress` calculates output for 
- Mean10HottestDays_VPD_kPa_F1
- Mean10HottestDays_VPD_kPa_MoistureStress_SWPcritXkPa_S_F1

where
- F1 is one of `mean` and `max` and
- S is one of `allLayers`, `topLayer`, and `bottomLayer`

New output variables for cold and dry conditions will be calculated analogously
- Mean10ColdestDays_VPD_kPa_F2
- Mean10ColdestSnowfreeDays_VPD_kPa_F2
- Mean10ColdestDays_VPD_kPa_MoistureStress_SWPcritXkPa_S_F2
- Mean10ColdestSnowfreeDays_VPD_kPa_MoistureStress_SWPcritXkPa_S_F2

where
- F2 is one of `mean` and `min`

**Comment by CaitlinA** [comment]
@Zachary-Kramer Please work on this enhancement

**Comment by CaitlinA** [comment]
@dschlaep 

Question about the current implementation of this aggregation:

Temperature does not appear to be evaluated as criteria for the calculation of the Mean10HottestDays_VPD_kPa_F1. Instead, it appears that the mean or max of top ten highest VPD values is calculated when SWP is also < SWPcrit.

Should we change this aggregation to look at the VPD on the 10 hottest or coldest days (or coldest & snow free) when SWP is also < SWPcrit?

**Comment by CaitlinA** [comment]
@dschlaep 

So John and I discussed these variables earlier today.

John suggested for the new variables, we calculate mean and min coldest temp instead of VPD.

So the new variables would be:

* Mean10ColdestDays_Temp_kPa_F2
* Mean10ColdestSnowfreeDays_Temp_kPa_F2
* Mean10ColdestDays_Temp_kPa_MoistureStress_SWPcritXkPa_S_F2
* Mean10ColdestSnowfreeDays_Temp_kPa_MoistureStress_SWPcritXkPa_S_F2

where:

* F2 is one of mean and min
* S is one of allLayers, topLayer, and bottomLayer

How does that sound to you?

**Comment by dschlaep** [comment]
> Re: Question about the current implementation of this aggregation:

I agree. The code doesn't do what the documentation claims it should, taking the mean of VPD during the 10 hottest days (as in air temperature) and during the 10 hottest days when soils are dry, respectively.

> So the new variables would be:
I am fine with these changes; these are all outputs for John's research. He determines what is best.
Do you suggest to keep the (fixed) previous ones? Or convert them to take the mean temperature instead of VPD?

**Comment by CaitlinA** [comment]
The plan is to keep/fix the previous ones and then add the new variables as above. 

Fixed the previous fields with commit https://github.com/DrylandEcology/rSFSW2/commit/5dd34c558973c0324146c2d2b59e0ed743824afd
