### ISSUE TITLE
Output aggregation: snow-free cold-degree days

### ISSUE THREAD

**Issue by dschlaep** [DrylandEcology/rSFSW2#225]
New output option `dailyColdDegreeDays` with output variable
- `ColdDegreeDays_BaseXC_dailyTmean_Cdays` = Cold-degree day sum with base X C ( Cxdays)
- `ColdDegreeDays_SnowFree_BaseXC_dailyTmean_Cdays` = Snow-free cold-degree day sum with base X C ( Cxdays)

This calculates analogously to degree-days. 
```
ids <- temp.dy$mean < opt_agg[["Tbase_coldDD_C"]]
colddegday <- ifelse(ids, temp.dy$mean - opt_agg[["Tbase_coldDD_C"]], 0)

ids_snowfree <- ids & SWE.dy$val <= SFSW2_glovars[["tol"]]
colddegday_snowfree <- ifelse(ids_snowfree, temp.dy$mean - opt_agg[["Tbase_coldDD_C"]], 0)
```

**Comment by CaitlinA** [comment]
@dschlaep 

Is the above suggested "SFSW2_glovars[["tol"]]" something that already exists?

If so, can you be more specific? If not, could this new variable be included as a opt_agg (i.e. opt_agg[["SWE_tol"]]

**Comment by dschlaep** [comment]
`SFSW2_glovars[["tol"]]` does exist and is currently used 50+ times in the existing code.

The environment variable `SFSW2_glovars` is defined in the file `R/rSFSW2-package.R`; the variable `tol` is created and a value assigned in the file `R/zzz.R`
```
assign("tol", sqrt(.Machine$double.eps), envir = SFSW2_glovars)
```

`SFSW2_glovars[["tol"]]` helps dealing with issues arising from floating point arithmetic. See `?all.equal` for some more details and [What Every Computer Scientist Should Know About Floating-Point Arithmetic](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html) provides some more background.

**Comment by Zachary-Kramer** [comment]
`opt_agg[["Tbase_coldDD_C"]]` does not exist, did you mean to refer to `opt_agg[["Tbase_DD_C"]]`? If not, what should the value be?

**Comment by dschlaep** [comment]
Correct, `opt_agg[["Tbase_coldDD_C"]]` is a new input that needs to be added to `demo/SFSW2_project_descriptions.R` in the list `opt_agg` near `Tbase_DD_C` on line 645. Set it to `0 C` for now:
```
  # Base temperature (degree C) below which cold-degree-days are accumulated
  Tbase_coldDD_C = 0,
```
