### ISSUE TITLE
DayMet unit tests fail

### ISSUE THREAD

**Issue by dschlaep** [DrylandEcology/rSFSW2#230]
```
Error: DayMet weather data: (@test_WeatherDB_DayMet.R#49) 
subscript out of bounds
1: dw_DayMet_NorthAmerica(dw_source, dw_names, exinfo, site_dat, 
       sim_time, path = dm_path) at rSFSW2/tests/testthat/test_WeatherDB_DayMet.R:49
```

**Comment by CaitlinA** [comment]
When running devtools::check() on local and on CI, all tests pass.

When running devtools::tests() on my local machine lines #69 and #70 in test_WeatherDB-DayMet.R daily.

<img width="1245" alt="screen shot 2018-01-03 at 2 19 16 pm" src="https://user-images.githubusercontent.com/13442815/34540266-25bb91b8-f091-11e7-8be7-47a9bead3c58.png">

**Comment by dschlaep** [comment]
@CaitlinA 
So, the code is telling us that the elements of list `x` are not instances of the class `swWeatherData` but instead `character`. I guess that may be the `message` attribute of an error class? Can you take a closer look at these objects?

**Comment by dschlaep** [comment]
The error arose because `avail_end_year` evaluated to `2017` but the 2017 data are not yet available. I'll push a fix.
