### ISSUE TITLE
Output Aggregation: Number of cold, snow-free days

### ISSUE THREAD

**Issue by CaitlinA** [DrylandEcology/rSFSW2#242]
Comparable to how dailyHotDays, dailyColdDays, and dailyCool days. New aggregation option "dailyColdSnowfreeDays"

Counts the number of days where:
* temp.dy$min < opt_agg[["Tbase_coldDD_C"]] 

* SWE.dy$val <= SFSW2_glovars[["tol"]]

**Comment by Zachary-Kramer** [comment]
This sounds like it is similar to the snow-free aggregation already in dailyColdDays. Could you clarify what is different? Or are you just separating the snow-free aggregation into its own option?

**Comment by CaitlinA** [comment]
It is just a count of the number of days. I will be working on it.

**Comment by CaitlinA** [comment]
Actually, this is the option dailyFrostInSnowfreePeriod.

I will be making edits though so the user can specify a span of days within a year for which to take a sum. This is so Bob Shriver can get specific variables necessary for model prediction when the decadal aggregations are complete.

**Comment by CaitlinA** [comment]
@dschlaep 

Just committed initial changes with commit. Not functional to run yet.

How do you feel about this approach for implementing additional aggregations to already functional aggregation options, but the calculation is only applied to a particular range of days (contained within one year)? 

- In the descriptions file in the opt_agg section the user sets whether they want to implement daily ranges or not, and the range of values they would like to use:

```
opt_agg[[use_daily_range]] <- TRUE
opt_agg[[daily_range_values]] <- c(1, 250) #min and max
```

- If use_daily_range is set to TRUE then an additional aggregation, on top of the existing aggregation that takes places for the entire year, is calculated.

- This is applied by creating a logical string where if the day of the year is within the daily range of values it is set to TRUE. If not, it is set to FALSe (`dailyrange` in the Simulation_Run.R file). Right now this creation of a logical string is in the aggregation itself, but because it will be potentially applied to multiple aggregations, I could either create a function to create it and call that function multiple times, or create it at the beginning of the aggregation code.

In the future, when we overhaul the aggregation outputs into functions, the use_daily_range could be applied to all daily aggregations. For now, I am planning on just applying this daily range to the variables necessary for Bob's project (frostInSnowPeriod and peak SWE)

Also, I realize a limit is that the values need to fall within one year. It is probably feasible to use logic like that of the "snowyears" variable to allow the calculation span years. What do you think?

**Comment by dschlaep** [comment]
Can you please clarify for me: Would the following
```
opt_agg[[daily_range_values]] <- c(1, 250) #min and max
```

calculate the output 
- as a function of the daily values of one year from day of the year 1 to 250
or
- as an aggregation across years where the daily values from each year from day of the year 1 to 250 are used?

If the second, then I suggest to rename `opt_agg[[daily_range_values]]` to `opt_agg[["doy_range"]]` or similar.

##
> This is applied by creating a logical string where if the day of the year is within the daily range of values it is set to TRUE. If not, it is set to FALSe (dailyrange in the Simulation_Run.R file).

I don't understand what a `logical string` is -- do you refer to a `logical vector` of the length of the total number of days in the rSOILWAT2 output?

If so, then I would add this vector as a new element into `simTime2` which is calculated/returned by function `simTiming_ForEachUsedTimeUnit` and is designed to be responsible for the selection/sub-setting of values for aggregation.

##
> Also, I realize a limit is that the values need to fall within one year. It is probably feasible to use logic like that of the "snowyears" variable to allow the calculation span years. What do you think?

I am not quite sure that the question is here? 
- Is the question that day of year "DOY" values are always within one calendar year, but that water years would be more meaningful? -- I see no problem with this and would probably be the right thing to do for snow-related variables.
or
- Is the question that these new type of aggregations should aggregate across more than one year? -- I would be need more arguments to believe that this would be a good idea.

In any case, the implementation should also consider northern/southern hemisphere issues (as dealt with by function `simTiming_ForEachUsedTimeUnit`).

**Comment by CaitlinA** [comment]
Thanks for your response.

It is an aggregation 

> across years where the daily values from each year from day of the year 1 to 250 are used.

Yes, I meant a vector.

Are snowyears and wateryears synonymous? They appear to be the same in the code. 

I suppose the answer to your last question is the first option. There should be the option to calculate within a water year (which spans across traditional years)

To ensure I understand the snowyear logic, lets run through an example.

Say a user wanted the dailyFrostInSnowfreePeriod from Nov 1st, Year X to Feb1st, Year X + 1.

```
opt_agg[[daily_range_values]] <- c(305, 31)

#simTime2$doy_ForEachUsedDay_dailyRange - additional output created with simTiming_ForEachUsedTimeUnit. TRUE or FALSE depending if the day of year falls within specified range

snowyears <- simTime2$year_ForEachUsedDay_NSadj + ifelse(simTime2$doy_ForEachUsedDay_NSadj > 273, 1, 0) )
          adjDays <- ifelse(simTime2$doy_ForEachUsedDay[1] == simTime2$doy_ForEachUsedDay_NSadj[1], 365 - 273, -91)
 
dailyrangeAdj <- simTime2$doy_ForEachUsedDay_dailyRange  + adjDays # these would need to be adjusted to reflect snow years

frostWithoutSnowDailyRange <- SWE.dy$val == 0 & temp.dy$min < iTmin & dailyrangeAdj)

frostWithoutSnowDailyRange <- tapply(frostWithoutSnowDailyRange, snowyears, sum)  #Numbers of days with min.temp < 0 and snow == 0 within daily range

```

Is that the gist of a correct approach?

Next, say the user had defined the same doy_range, but wanted a different variable that does _not_ incorporate water years (i.e. the sum of VWC). Then we would be crossing different years, which I think we should avoid for now. Should there be different doy_ranges that can be set? One for variables that uses snowyears and one that does not?

Should there be a way to set different doy_ranges because you want different ranges for different variables, regardless of the snow years problem? For example, for Bob's research we will need output aggregated over DOY 1-250 for some, and DOY 1-70 for another (Issue #246)? I imagine, the code would loop over and aggregate over each different range.... But then we would also need different outputs in the simTime2 output that reflects this.

**Comment by dschlaep** [comment]
Yes,  snowyears and water years are the same. Their 'official' name is `water year` which starts on Oct 1 in the northern hemisphere (https://en.wikipedia.org/wiki/Water_year)

**Comment by dschlaep** [comment]
> dailyrangeAdj <- simTime2$doy_ForEachUsedDay_dailyRange  + adjDays

From an earlier explanation `doy_ForEachUsedDay_dailyRange` would be a logical vector, but here it looks like it is more of a positional index vector? `adjDays` is a number; you can add that to a logical value in R, but the result is most likely not what you wanted.

**Comment by dschlaep** [comment]
> Should there be a way to set different doy_ranges because you want different ranges for different variables, regardless of the snow years problem?


What about making this explicit in the inputs?
```
opt_agg[["doy_range"]] <- list(
    dailySnowpack = c(305, 31),
    dailyFrostInSnowfreePeriod = c(1, 70))
```

maybe also allow a 'default' which is applied to those aggregations for which no specific doy-range is specified (if present)
```
opt_agg[["doy_range"]] <- list(
    dailySnowpack = c(305, 31),
    dailyFrostInSnowfreePeriod = c(1, 70),
    default = c(1, 250))
```
