### ISSUE TITLE
Output Aggregation: Sum of VWC across certain range of days

### ISSUE THREAD

**Issue by CaitlinA** [DrylandEcology/rSFSW2#246]
What is needed: Matric Volumetric water content of 0-5 cm (Day 71-100)--Sum of all days VWC over period

**Comment by CaitlinA** [comment]
@dschlaep 

This variable is so specific that I feel uncertain where to add into the aggregation options and how rigorously to set it up.

Could we add a new aggregation option:

'dailyVWCsum' -> sum VWC for both the days of the year and also the specific range? And then also across opt_agg[["doy_slyrs"]]? If this is the case, the "first soil layer" would need to be set to 5cm for the decadal runs.

Alternatively, I just create a one-off aggregation that calculates just the above specifically, and we don't maintain it into the future.

What do you think?

**Comment by dschlaep** [comment]
How is this different from the suggestions 
```
opt_agg[[use_daily_range]] <- TRUE
opt_agg[[daily_range_values]] <- c(1, 250) #min and max
```
in #242?

##
> the "first soil layer" would need to be set to 5cm for the decadal runs.

We use 
```
requested_soil_layers = c(5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 150)
```
for the soil layers in the decadal project. So that should not be a problem.

**Comment by CaitlinA** [comment]
It is similar.

Do you agree that the total sum of VWC should be taken for a year then, and then also the specific doy_range?

Do you have a suggested place in the `overall_out` to place this new variable?

**Comment by dschlaep** [comment]
I would place it among `#---Aggregation: Ecological dryness` as it is a soil moisture measure or make a new one for soil moisture only.

btw, I don't understand why the sum of VWC would be meaningful -- and separate from mean VWC? VWC is a relative measure (volume water / volume soil) and I don't see how a sum could yield a meaningful variable. Are you sure that Bob really needs the sum of VWC and not the sum of SWC or SWA?
