### ISSUE TITLE
icheck stops simulations under wrong conditions

### ISSUE THREAD

**Issue by CaitlinA** [DrylandEcology/rSFSW2#286]
```
`icheck <- "PotentialNaturalVegetation_CompositionShrubsC3C4_Paruelo1996" %in%
      SFSW2_prj_inputs[["create_treatments"]] &&
      any(pnv_temp %in% SFSW2_prj_inputs[["create_treatments"]])

   if (any(!icheck)) {
      stop("Calculation and/or adjustement of 'potential natural vegetation' is ",
        "requested for some composition/biomass/root components: the column ",
        "'PotentialNaturalVegetation_CompositionShrubsC3C4_Paruelo1996' is the overall ",
        "gate-keeper for this suit of functionality and must thus be turned on as well ",
        "but is currently not.")
    }
`
```
in Simulation_project.R stops simulation when ALL PotentialNaturalVegetation_CompositionShrubsC3C4_Paruelo1996 options are turned off, aka the user is inputting all vegetation in the prod file.

I believe the original intent is to check that some options reliant on the "PotentialNaturalVegetation_CompositionShrubsC3C4_Paruelo1996" are not turned on when the main "PotentialNaturalVegetation_CompositionShrubsC3C4_Paruelo1996" is turned off. Correct?

**Comment by dschlaep** [comment]
Agreed.

Looks like this should be
```
pnv0_temp <- "PotentialNaturalVegetation_CompositionShrubsC3C4_Paruelo1996"
temp1 <- pnv0_temp %in% SFSW2_prj_inputs[["create_treatments"]]
temp2 <- pnv_temp %in% SFSW2_prj_inputs[["create_treatments"]]

icheck <- (!temp1 && all(!temp2)) || (temp1 && any(temp2))
```

i.e., either 
	none of the `PotentialNaturalVegetation_*` columns are turned on
or
	PotentialNaturalVegetation_CompositionShrubsC3C4_Paruelo1996 is active and at least one other

What do you think?
