### ISSUE TITLE
Move SSURGO site metadata elsewhere

### ISSUE THREAD

**Issue by Zachary-Kramer** [DrylandEcology/rSFSW2#288]
Currently metadata for a site's SSURGO extraction is stored in `sw_input_soillayers` to be easily accessible with the site. The current metadata is: `mukey`, `cokey`, and `comppct`. `cokey` is also trying to be moved elsewhere with #283.

One issue I just ran into is that the function `check_monotonic_increase` obviously reads in this metadata as values. This can be an issue when, say, the `mukey` is `55243` and the `comppct` is `40`; there is no longer a monotonic increase and thus fails. There are a few solutions to this specific issue, but the underlying issue is that metadata is being mixed with real data and that will have various complications.

I agree with @dschlaep 's opinion about metadata:

> I'm fine with storing that additional information, but I think that appending such metadata to our existing tables is counterproductive speed and memory-wise. I am fine with storing it as an additional file somewhere, what about under 0_Metadata?

Thus, the metadata should be removed from `sw_input_soillayers` and stored elsewhere.

**Comment by Zachary-Kramer** [comment]
In the meantime I have disabled the writing of metadata via comments and I reference this issue within the code in commit e912973865f986e7b209a71bfc651f2e9124d377

**Comment by CaitlinA** [comment]
I think this being disabled is Alright. 

This iteration of SSURGO will be replaced by the gridded SSURGO resource.
