### ISSUE TITLE
Where in Test4_OverallAggregations_snow is SWRuns_InputMaster_Test_v11.csv created

### ISSUE THREAD

**Issue by nip5** [DrylandEcology/rSFSW2#318]
I have been stuck on this for some time, I can find where the file is being used as an input but cannot find where it is created in the first place but maybe you know @dschlaep . I need to be able to modify it for issue #305.

**Comment by dschlaep** [comment]
This file is not created. It exists at `Test4_AllOverallAggregations_snow/1_Data_SWInput/`

**Comment by dschlaep** [comment]
However, the original file that is used for any application of this package is at `/data-raw/1_Data_SWInput/`. The copy in `tests/test_data/Test4_AllOverallAggregations_snow/1_Data_SWInput/` must match the original one in design.

Also note the README section `Updates to input files and/or demo code`
