### ISSUE TITLE
'update_actions' function fails when wipe_dbOutput == FALSE

### ISSUE THREAD

**Issue by CaitlinA** [DrylandEcology/rSFSW2#320]
When `wipe_dbOutput= FALSE` the function update_actions fails with this error message:

`Error in sum(actions) : invalid 'type' (list) of argument`

Perhaps `length(actions)` would do the trick?

**Comment by dschlaep** [comment]
i.e., if you run in parallel, then each worker must have the correct version -- which is not possible with `devtools::load_all()`. If you run in parallel, then you need to have a properly installed one with `R CMD install .`

**Comment by dschlaep** [comment]
ok, but I can change to `sum(unlist(actions))` which should do what you request anyhow!

**Comment by CaitlinA** [comment]
Thanks Daniel!
